# Generated by Django 5.2.15 on 2026-06-10 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CURATED_OPENAI_MODELS = [
    ("gpt-5.5", "GPT-5.5", 10),
    ("gpt-5.4", "GPT-5.4", 20),
    ("gpt-5.4-mini", "GPT-5.4 mini", 30),
    ("gpt-5.4-nano", "GPT-5.4 nano", 40),
    ("gpt-4.1", "GPT-4.1", 50),
    ("gpt-4.1-mini", "GPT-4.1 mini", 60),
    ("gpt-4.1-nano", "GPT-4.1 nano", 70),
]

CURATED_MODELS = {
    "anthropic": [
        ("claude-opus-4-8", "Claude Opus 4.8", 10),
        ("claude-sonnet-4-6", "Claude Sonnet 4.6", 20),
        ("claude-haiku-4-5", "Claude Haiku 4.5", 30),
    ],
    "gemini": [
        ("gemini-3.5-flash", "Gemini 3.5 Flash", 10),
        ("gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview", 20),
        ("gemini-3-flash-preview", "Gemini 3 Flash Preview", 30),
        ("gemini-3.1-flash-lite", "Gemini 3.1 Flash-Lite", 40),
        ("gemini-2.5-pro", "Gemini 2.5 Pro", 50),
        ("gemini-2.5-flash", "Gemini 2.5 Flash", 60),
        ("gemini-2.5-flash-lite", "Gemini 2.5 Flash-Lite", 70),
    ],
}


def seed_openai_model_catalog(apps, schema_editor):
    AIModelCatalog = apps.get_model("core", "AIModelCatalog")
    for model_id, display_name, sort_order in CURATED_OPENAI_MODELS:
        AIModelCatalog.objects.update_or_create(
            provider="openai",
            model_id=model_id,
            defaults={
                "display_name": display_name,
                "enabled": True,
                "sort_order": sort_order,
            },
        )


def unseed_openai_model_catalog(apps, schema_editor):
    AIModelCatalog = apps.get_model("core", "AIModelCatalog")
    AIModelCatalog.objects.filter(
        provider="openai",
        model_id__in=[
            model_id
            for model_id, _display_name, _sort_order in CURATED_OPENAI_MODELS
        ],
    ).delete()


def seed_model_catalog(apps, schema_editor):
    AIModelCatalog = apps.get_model("core", "AIModelCatalog")
    for provider, models_for_provider in CURATED_MODELS.items():
        for model_id, display_name, sort_order in models_for_provider:
            AIModelCatalog.objects.update_or_create(
                provider=provider,
                model_id=model_id,
                defaults={
                    "display_name": display_name,
                    "enabled": True,
                    "sort_order": sort_order,
                },
            )


def unseed_model_catalog(apps, schema_editor):
    AIModelCatalog = apps.get_model("core", "AIModelCatalog")
    for provider, models_for_provider in CURATED_MODELS.items():
        AIModelCatalog.objects.filter(
            provider=provider,
            model_id__in=[
                model_id
                for model_id, _display_name, _sort_order in models_for_provider
            ],
        ).delete()


def migrate_other_to_custom(apps, schema_editor):
    DatabaseConnection = apps.get_model("core", "DatabaseConnection")
    DatabaseConnection.objects.filter(provider="other").update(provider="custom")


def migrate_custom_to_other(apps, schema_editor):
    DatabaseConnection = apps.get_model("core", "DatabaseConnection")
    DatabaseConnection.objects.filter(provider="custom").update(provider="other")

class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_aiproviderkey'), ('core', '0003_alter_membership_options'), ('core', '0004_aiprovidermodel'), ('core', '0005_alter_aiproviderkey_model_name'), ('core', '0006_aimodelcatalog'), ('core', '0007_seed_openai_model_catalog'), ('core', '0008_remove_aiproviderkey_enabled'), ('core', '0009_alter_aimodelcatalog_provider_and_more'), ('core', '0010_seed_claude_gemini_model_catalog'), ('core', '0011_databaseconnection'), ('core', '0012_alter_databaseconnection_provider'), ('core', '0013_queryexecutionlog'), ('core', '0014_report_reportchatmessage'), ('core', '0015_report_ai_model_name_and_more'), ('core', '0016_reportchatmessage_artifact'), ('core', '0017_report_shared_with_report_sharing_scope'), ('core', '0018_queryexecutionlog_cache_status_reportdatasetcache'), ('core', '0019_reportdatasetcachelock'), ('core', '0020_organization_security_policies'), ('core', '0021_organization_sso_oidc'), ('core', '0022_organization_report_cache_enabled')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sso_required', models.BooleanField(default=False)),
                ('query_timeout_seconds', models.PositiveIntegerField(default=120)),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=86400)),
                ('max_rows', models.PositiveIntegerField(default=50000)),
                ('max_raw_bytes', models.PositiveBigIntegerField(default=52428800)),
                ('max_compressed_bytes', models.PositiveBigIntegerField(default=10485760)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=30)),
                ('name', models.CharField(default='OpenAI', max_length=255)),
                ('model_name', models.CharField(default='gpt-5.4-mini', max_length=255)),
                ('encrypted_api_key', models.TextField()),
                ('key_last_four', models.CharField(blank=True, max_length=4)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_keys', to='core.organization')),
            ],
            options={
                'ordering': ['provider', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'name'), name='unique_ai_provider_key_name_per_organization')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Company admin'), ('creator', 'Creator'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
            ],
            options={
                'ordering': ['organization__name', 'user__email'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_membership_per_organization_user')],
            },
        ),
        migrations.CreateModel(
            name='AIProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_model_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('allowed', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_models', to='core.aiproviderkey')),
            ],
            options={
                'ordering': ['provider_model_id'],
                'constraints': [models.UniqueConstraint(fields=('provider_key', 'provider_model_id'), name='unique_model_per_ai_provider_key')],
            },
        ),
        migrations.CreateModel(
            name='AIModelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=30)),
                ('model_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_id'), name='unique_ai_model_catalog_provider_model')],
            },
        ),
        migrations.RunPython(
            code=seed_openai_model_catalog,
            reverse_code=unseed_openai_model_catalog,
        ),
        migrations.RemoveField(
            model_name='aiproviderkey',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Claude'), ('gemini', 'Gemini')], default='openai', max_length=30),
        ),
        migrations.AlterField(
            model_name='aiproviderkey',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Claude'), ('gemini', 'Gemini')], default='openai', max_length=30),
        ),
        migrations.RunPython(
            code=seed_model_catalog,
            reverse_code=unseed_model_catalog,
        ),
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('postgres', 'Postgres'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery'), ('sqlite', 'SQLite'), ('other', 'Other SQLAlchemy')], default='postgres', max_length=30)),
                ('encrypted_connection_string', models.TextField()),
                ('connection_string_preview', models.CharField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_succeeded', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_connections', to='core.organization')),
            ],
            options={
                'ordering': ['provider', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_database_connection_name_per_organization')],
            },
        ),
        migrations.RunPython(
            code=migrate_other_to_custom,
            reverse_code=migrate_custom_to_other,
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='provider',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery'), ('sqlite', 'SQLite'), ('custom', 'Custom connection string')], default='postgres', max_length=30),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled report', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('html', models.TextField(blank=True)),
                ('primary_sql', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_provider_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.aiproviderkey')),
                ('database_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.databaseconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_reports', to=settings.AUTH_USER_MODEL)),
                ('ai_model_name', models.CharField(blank=True, max_length=255)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
                ('sharing_scope', models.CharField(choices=[('private', 'Only me'), ('organization', 'Everyone in my organization')], default='private', max_length=20)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('artifact', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_preview', models.TextField(blank=True)),
                ('succeeded', models.BooleanField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_execution_logs', to='core.databaseconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_execution_logs', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_execution_logs', to=settings.AUTH_USER_MODEL)),
                ('cache_status', models.CharField(choices=[('miss', 'Cache miss'), ('hit', 'Cache hit'), ('bypass', 'Cache bypass')], default='miss', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDatasetCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(default='primary', max_length=100)),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('sql_preview', models.TextField(blank=True)),
                ('compressed_payload', models.BinaryField()),
                ('raw_bytes', models.PositiveBigIntegerField()),
                ('compressed_bytes', models.PositiveBigIntegerField()),
                ('row_count', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_dataset_caches', to='core.databaseconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_dataset_caches', to='core.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_caches', to='core.report')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['report', 'dataset_name', 'expires_at'], name='core_report_report__30b70c_idx'), models.Index(fields=['organization', 'expires_at'], name='core_report_organiz_ce5f75_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportDatasetCacheLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='report_ip_allowlist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_ip_allowlist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_url_whitelist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_url_whitelist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_url_blacklist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_url_blacklist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sso_oidc_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='sso_oidc_issuer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sso_oidc_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='encrypted_sso_oidc_client_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sso_oidc_client_secret_last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='organization',
            name='sso_oidc_scopes',
            field=models.CharField(default='openid email profile', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_cache_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
