# Generated by Django 5.2.15 on 2026-06-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=30)),
                ('name', models.CharField(default='OpenAI', max_length=255)),
                ('model_name', models.CharField(default='gpt-4.1', max_length=255)),
                ('encrypted_api_key', models.TextField()),
                ('key_last_four', models.CharField(blank=True, max_length=4)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_keys', to='core.organization')),
            ],
            options={
                'ordering': ['provider', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'name'), name='unique_ai_provider_key_name_per_organization')],
            },
        ),
    ]
