# Generated by Django 5.2.15 on 2026-06-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiproviderkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['organization__name', 'user__email']},
        ),
    ]
