# Generated by Django 5.2.15 on 2026-06-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_membership_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_model_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('allowed', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_models', to='core.aiproviderkey')),
            ],
            options={
                'ordering': ['provider_model_id'],
                'constraints': [models.UniqueConstraint(fields=('provider_key', 'provider_model_id'), name='unique_model_per_ai_provider_key')],
            },
        ),
    ]
