# Generated by Django 5.2.15 on 2026-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aiprovidermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderkey',
            name='model_name',
            field=models.CharField(default='gpt-5.4-mini', max_length=255),
        ),
    ]
