# Generated by Django 5.2.15 on 2026-06-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aiproviderkey_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=30)),
                ('model_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_id'), name='unique_ai_model_catalog_provider_model')],
            },
        ),
    ]
