# Generated by Django 5.2.15 on 2026-06-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_openai_model_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiproviderkey',
            name='enabled',
        ),
    ]
