# Generated by Django 5.2.15 on 2026-06-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_aiproviderkey_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelcatalog',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Claude'), ('gemini', 'Gemini')], default='openai', max_length=30),
        ),
        migrations.AlterField(
            model_name='aiproviderkey',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Claude'), ('gemini', 'Gemini')], default='openai', max_length=30),
        ),
    ]
