# Generated by Django 5.2.15 on 2026-06-08 18:56

from django.db import migrations


CURATED_MODELS = {
    "anthropic": [
        ("claude-opus-4-8", "Claude Opus 4.8", 10),
        ("claude-sonnet-4-6", "Claude Sonnet 4.6", 20),
        ("claude-haiku-4-5", "Claude Haiku 4.5", 30),
    ],
    "gemini": [
        ("gemini-3.5-flash", "Gemini 3.5 Flash", 10),
        ("gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview", 20),
        ("gemini-3-flash-preview", "Gemini 3 Flash Preview", 30),
        ("gemini-3.1-flash-lite", "Gemini 3.1 Flash-Lite", 40),
        ("gemini-2.5-pro", "Gemini 2.5 Pro", 50),
        ("gemini-2.5-flash", "Gemini 2.5 Flash", 60),
        ("gemini-2.5-flash-lite", "Gemini 2.5 Flash-Lite", 70),
    ],
}


def seed_model_catalog(apps, schema_editor):
    AIModelCatalog = apps.get_model("core", "AIModelCatalog")
    for provider, models in CURATED_MODELS.items():
        for model_id, display_name, sort_order in models:
            AIModelCatalog.objects.update_or_create(
                provider=provider,
                model_id=model_id,
                defaults={
                    "display_name": display_name,
                    "enabled": True,
                    "sort_order": sort_order,
                },
            )


def unseed_model_catalog(apps, schema_editor):
    AIModelCatalog = apps.get_model("core", "AIModelCatalog")
    for provider, models in CURATED_MODELS.items():
        AIModelCatalog.objects.filter(
            provider=provider,
            model_id__in=[
                model_id for model_id, _display_name, _sort_order in models
            ],
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_aimodelcatalog_provider_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_model_catalog, unseed_model_catalog),
    ]
