# Generated by Django 5.2.15 on 2026-06-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_claude_gemini_model_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('postgres', 'Postgres'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery'), ('sqlite', 'SQLite'), ('other', 'Other SQLAlchemy')], default='postgres', max_length=30)),
                ('encrypted_connection_string', models.TextField()),
                ('connection_string_preview', models.CharField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_succeeded', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_connections', to='core.organization')),
            ],
            options={
                'ordering': ['provider', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_database_connection_name_per_organization')],
            },
        ),
    ]
