# Generated by Django 5.2.15 on 2026-06-08 22:23

from django.db import migrations, models


def migrate_other_to_custom(apps, schema_editor):
    DatabaseConnection = apps.get_model("core", "DatabaseConnection")
    DatabaseConnection.objects.filter(provider="other").update(provider="custom")


def migrate_custom_to_other(apps, schema_editor):
    DatabaseConnection = apps.get_model("core", "DatabaseConnection")
    DatabaseConnection.objects.filter(provider="custom").update(provider="other")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_databaseconnection'),
    ]

    operations = [
        migrations.RunPython(migrate_other_to_custom, migrate_custom_to_other),
        migrations.AlterField(
            model_name='databaseconnection',
            name='provider',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery'), ('sqlite', 'SQLite'), ('custom', 'Custom connection string')], default='postgres', max_length=30),
        ),
    ]
