# Generated by Django 5.2.15 on 2026-06-08 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_report_reportchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_model_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='database_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.databaseconnection'),
        ),
    ]
