# Generated by Django 5.2.15 on 2026-06-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_report_ai_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportchatmessage',
            name='artifact',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
