# Generated by Django 5.2.15 on 2026-06-09 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_reportchatmessage_artifact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='sharing_scope',
            field=models.CharField(choices=[('private', 'Only me'), ('organization', 'Everyone in my organization')], default='private', max_length=20),
        ),
    ]
