# Generated by Django 5.2.15 on 2026-06-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_report_shared_with_report_sharing_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryexecutionlog',
            name='cache_status',
            field=models.CharField(choices=[('miss', 'Cache miss'), ('hit', 'Cache hit'), ('bypass', 'Cache bypass')], default='miss', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportDatasetCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(default='primary', max_length=100)),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('sql_preview', models.TextField(blank=True)),
                ('compressed_payload', models.BinaryField()),
                ('raw_bytes', models.PositiveBigIntegerField()),
                ('compressed_bytes', models.PositiveBigIntegerField()),
                ('row_count', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_dataset_caches', to='core.databaseconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_dataset_caches', to='core.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_caches', to='core.report')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['report', 'dataset_name', 'expires_at'], name='core_report_report__30b70c_idx'), models.Index(fields=['organization', 'expires_at'], name='core_report_organiz_ce5f75_idx')],
            },
        ),
    ]
