# Generated by Django 5.2.15 on 2026-06-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_organization_sso_oidc'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='report_cache_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
